
###
POST http://localhost:5500/cloud/login
Content-Type: application/json

{"username":"admin","password":"admin"}

###
GET http://localhost:5500/api/v1/admin/users/20/0
Content-Type: application/json
auth-token: Bearer {TOKEN}

###
GET http://localhost:5500/api/v1/admin/users/1
Content-Type: application/json
auth-token: Bearer {TOKEN}

###
GET http://localhost:5500/api/v1/admin/users/page/0
Content-Type: application/json
auth-token: Bearer {TOKEN}

###
POST http://localhost:5500/api/v1/admin/users
Content-Type: application/json
auth-token: Bearer {TOKEN}

{"pageNum": 0}

###
POST http://localhost:5500/cloud/logout
Content-Type: application/json
auth-token: Bearer {TOKEN}

